# Makes small copies of every car photo (480 px and 800 px wide) so phones download a small file instead of the big one.
# Run only when you ADD or CHANGE a car photo:   python3 scripts/make-image-sizes.py
# It also rewrites src/data/imageSets.js (the list of which sizes exist). Needs: pip install pillow
import glob, os, re, json
from PIL import Image
D = "public/assets/vehicles"
WIDTHS = [480, 800]
sets = {}
for f in sorted(glob.glob(f"{D}/*.webp")):
    name = os.path.basename(f)[:-5]
    if re.search(r"-(480|800)$", name): continue
    im = Image.open(f); im.load(); w, h = im.size
    ws = []
    for t in WIDTHS:
        if t >= w * 0.9: continue
        out = im.resize((t, round(h * t / w)), Image.LANCZOS)
        out.save(f"{D}/{name}-{t}.webp", "WEBP", quality=80, method=4)
        ws.append(t)
    ws.append(w); sets[name] = ws
    print(name, ws, [os.path.getsize(f"{D}/{name}-{t}.webp")//1024 if t != w else os.path.getsize(f)//1024 for t in ws], "KB")
js = "// AUTO-GENERATED by scripts/make-image-sizes.py - do not edit by hand.\n// For each car photo: the widths (px) that exist. The biggest is the original file.\nexport const SETS = " + json.dumps(sets, indent=1) + ";\n"
open("src/data/imageSets.js", "w").write(js)
